repos:

- repo: local
  hooks:
  - id: flake8
    name: flake8
    entry: flake8 app --config=.flake8
    language: system
    types: [python]
    stages: [commit]
    require_serial: true

  - id: pylint
    name: pylint
    entry: pylint app --rcfile=.pylintrc
    language: system
    types: [python]
    stages: [commit]
    require_serial: true

  - id: pyright
    name: pyright
    entry: pyright app
    language: system
    types: [python]
    stages: [commit]
    require_serial: true
