name: DocHub CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest --html=test_report/test-report.html --cov=app/ --cov-report=html --cov-config=.coveragerc

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: pytest-test-report
        path: test_report/test-report.html

    - name: Upload test coverage report
      uses: actions/upload-artifact@v3
      with:
        name: pytest-coverage-report
        path: htmlcov/index.html

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 app/ --config=.flake8

    - name: Lint with pylint
      run: |
        pylint app/ --rcfile=.pylintrc
